"""Add fee rates table

Revision ID: 341f5c91035d
Revises: d3e078ae45c3
Create Date: 2026-07-28 19:24:09.961389

"""
from alembic import op
import sqlalchemy as sa


revision = '341f5c91035d'
down_revision = 'd3e078ae45c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fee_rates')
    # ### end Alembic commands ###
