"""Add specialty column to billing

Revision ID: caa0fb430153
Revises: 341f5c91035d
Create Date: 2026-07-30 09:37:43.589814

"""
from alembic import op
import sqlalchemy as sa


revision = 'caa0fb430153'
down_revision = '341f5c91035d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing', schema=None) as batch_op:
        batch_op.drop_column('specialty')

    # ### end Alembic commands ###
